#if !canImport(ObjectiveC)
import XCTest

extension ABICodableTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ABICodableTests = [
        ("testAbiCoding", testAbiCoding),
        ("testAbiSpec", testAbiSpec),
        ("testSigningRequest", testSigningRequest),
        ("testTransfer", testTransfer),
        ("testUntypedAbi", testUntypedAbi),
    ]
}

extension TypeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TypeTests = [
        ("testAsset", testAsset),
        ("testAssetSymbol", testAssetSymbol),
        ("testName", testName),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ABICodableTests.__allTests__ABICodableTests),
        testCase(TypeTests.__allTests__TypeTests),
    ]
}
#endif
