#if !canImport(ObjectiveC)
    import XCTest

    extension ABICodableTests {
        // DO NOT MODIFY: This is autogenerated, use:
        //   `swift test --generate-linuxmain`
        // to regenerate.
        static let __allTests__ABICodableTests = [
            ("testAbiCoding", testAbiCoding),
            ("testAbiSpec", testAbiSpec),
            ("testComplexAbi", testComplexAbi),
            ("testPermissionLevel", testPermissionLevel),
            ("testPublicKey", testPublicKey),
            ("testSignature", testSignature),
            ("testTransfer", testTransfer),
            ("testUntypedAbi", testUntypedAbi),
        ]
    }

    extension APITests {
        // DO NOT MODIFY: This is autogenerated, use:
        //   `swift test --generate-linuxmain`
        // to regenerate.
        static let __allTests__APITests = [
            ("testErrorMessage", testErrorMessage),
            ("testGetAccount", testGetAccount),
            ("testGetAccountsByAuthorizersUsingAccount", testGetAccountsByAuthorizersUsingAccount),
            ("testGetAccountsByAuthorizersUsingKey", testGetAccountsByAuthorizersUsingKey),
            ("testGetInfo", testGetInfo),
            ("testGetKeyAccounts", testGetKeyAccounts),
            ("testGetRawAbi", testGetRawAbi),
            ("testGetTableRows", testGetTableRows),
            ("testPushTransaction", testPushTransaction),
        ]
    }

    extension Base58Test {
        // DO NOT MODIFY: This is autogenerated, use:
        //   `swift test --generate-linuxmain`
        // to regenerate.
        static let __allTests__Base58Test = [
            ("testDecode", testDecode),
            ("testEncode", testEncode),
            ("testLargeDecode", testLargeDecode),
            ("testLargeEncode", testLargeEncode),
            ("testRipemd160", testRipemd160),
        ]
    }

    extension CryptoTests {
        // DO NOT MODIFY: This is autogenerated, use:
        //   `swift test --generate-linuxmain`
        // to regenerate.
        static let __allTests__CryptoTests = [
            ("testEncodeDecode", testEncodeDecode),
            ("testSharedSecret", testSharedSecret),
            ("testSignsAndVerifies", testSignsAndVerifies),
        ]
    }

    extension Secp256k1Test {
        // DO NOT MODIFY: This is autogenerated, use:
        //   `swift test --generate-linuxmain`
        // to regenerate.
        static let __allTests__Secp256k1Test = [
            ("testCustomContext", testCustomContext),
            ("testPublicFromPrivate", testPublicFromPrivate),
            ("testRandomizes", testRandomizes),
            ("testSharedSecret", testSharedSecret),
            ("testSignAndRecover", testSignAndRecover),
            ("testVerifiesSecret", testVerifiesSecret),
        ]
    }

    extension SigningRequestTests {
        // DO NOT MODIFY: This is autogenerated, use:
        //   `swift test --generate-linuxmain`
        // to regenerate.
        static let __allTests__SigningRequestTests = [
            ("testComplexMetadata", testComplexMetadata),
            ("testCreateResolve", testCreateResolve),
            ("testCreateSigned", testCreateSigned),
            ("testEncodeDecode", testEncodeDecode),
            ("testIdentity", testIdentity),
            ("testMetadata", testMetadata),
            ("testResolve", testResolve),
            ("testVerifySigned", testVerifySigned),
        ]
    }

    extension TypeTests {
        // DO NOT MODIFY: This is autogenerated, use:
        //   `swift test --generate-linuxmain`
        // to regenerate.
        static let __allTests__TypeTests = [
            ("testAsset", testAsset),
            ("testAssetSymbol", testAssetSymbol),
            ("testAuthority", testAuthority),
            ("testBlockId", testBlockId),
            ("testChecksum256", testChecksum256),
            ("testName", testName),
            ("testPublicKey", testPublicKey),
            ("testTimePoint", testTimePoint),
            ("testTransaction", testTransaction),
        ]
    }

    public func __allTests() -> [XCTestCaseEntry] {
        return [
            testCase(ABICodableTests.__allTests__ABICodableTests),
//            testCase(APITests.__allTests__APITests),
            testCase(Base58Test.__allTests__Base58Test),
            testCase(CryptoTests.__allTests__CryptoTests),
            testCase(Secp256k1Test.__allTests__Secp256k1Test),
//            testCase(SigningRequestTests.__allTests__SigningRequestTests),
            testCase(TypeTests.__allTests__TypeTests),
        ]
    }
#endif
